### ISSUE TITLE
Is this all of the code

### ISSUE THREAD

**Issue by saadb** [matthewjagiela/uSurf-iOS#1]
I was wondering if this is all of the swift code

**Comment by matthewjagiela** [comment]
Hi it isn't actually there is a lot more since I last pushed with a lot more functionality. Right now it is being worked on in small increments as I have a lot more things in the work and the non swift version is working still.

**Comment by saadb** [comment]
Thanx
Is the non swift code available to look at as a reference, I will not steal

**Comment by matthewjagiela** [comment]
It's in pretty rough shape and isn't the newest version which is why I am re-writing it. I'd be happy to help you and ill push my newest swift version to see if it helps you.

**Comment by saadb** [comment]
Thank you very much
